#!/usr/bin/env bash

# Get directory for symlink script.
DOTFILES_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

shopt -s dotglob
shopt -s extglob
shopt -s globstar
shopt -s nullglob

# Link to ~.
for f in "$DOTFILES_DIR"/system/!(*.template); do
  ln -sfv "$f" ~/
done

# Compile templates.
for template_name in "$DOTFILES_DIR"/**/*.template; do
  compiled_name=${template_name%.*}
  "$DOTFILES_DIR"/bin/xrdb-compile-colors "$template_name" "$compiled_name"
done

# Link to .config/$folder.
for folder in bash bspwm compton dunst feh git htop mpd mpv ncmpcpp polybar ranger rtorrent sxhkd tmux weechat zathura; do
  mkdir -pv ~/.config/$folder/
  for f in "$DOTFILES_DIR"/$folder/!(*.template); do
    ln -sfv "$f" ~/.config/$folder/
  done
done

# Link bin.
mkdir -pv ~/.local/bin/
for f in "$DOTFILES_DIR"/bin/!(*.template); do
  ln -sfv "$f" ~/.local/bin/
done

# Link gtk.
mkdir -pv ~/.config/gtk-3.0/
ln -sfv "$DOTFILES_DIR"/gtk/.gtkrc-2.0 ~/
ln -sfv "$DOTFILES_DIR"/gtk/settings.ini ~/.config/gtk-3.0/

# Link vim config.
mkdir -pv ~/.vim/
for f in "$DOTFILES_DIR"/vim/!(*.template); do
  ln -sfv "$f" ~/.vim/
done

# Link miscellaneous config.
mkdir -pv ~/.config/redshift/
ln -sfv "$DOTFILES_DIR"/misc/redshift.conf ~/.config/redshift/

# Create a playlist folder and database file for mpd.
mkdir -pv ~/.config/mpd/playlists/
touch ~/.config/mpd/database

# Create screenshot folder for mpv.
mkdir -pv ~/Pictures/Screenshots/

# Create complete, incomplete, and session folders for rtorrent.
mkdir -pv ~/Downloads/complete/ ~/Downloads/incomplete/ ~/.config/rtorrent/sessions/
