#!/bin/sh

# General bspwm configuration.
bspc config border_width 4
bspc config window_gap 0
bspc config top_padding 21
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

# Monocle configuration.
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config single_monocle true

# Pointer configuration.
bspc config click_to_focus button1
bspc config focus_follows_pointer true

# Monitor configuration.
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Color configuration.
eval "$(xrdb-export-colors)"
bspc config active_border_color "$COLOR_0"
bspc config focused_border_color "$COLOR_3"
bspc config normal_border_color "$COLOR_0"
bspc config presel_feedback_color "$COLOR_3"

# bspwm rules.
bspc rule --add Zathura state=tiled

# Initialize monitors.
init-monitors

# Change appearance of pointer.
xsetroot -cursor_name left_ptr

# Startup applications.
init-daemon --process dunst &
init-daemon --process mpd
init-daemon --process notify-battery &
init-daemon --process picom &
init-daemon --process robar --script "robar start" &
init-daemon --process robar-brightness-server &
init-daemon --process robar-volume-server &
init-daemon --process sxhkd &
init-daemon --process urxvtd --script "urxvtd --quiet --fork --opendisplay"

# Tray applets.
init-daemon --process blueman-applet &
init-daemon --process nm-applet &
init-daemon --process redshift-gtk &

# Initialize fonts.
xset +fp "$HOME/.local/share/fonts" && xset fp rehash
