#!/bin/sh

# General bspwm configuration.
bspc config border_width 4
bspc config window_gap 0
bspc config top_padding 21
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

# Monocle configuration.
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true

# Pointer configuration.
bspc config click_to_focus button1
bspc config focus_follows_pointer true

# Monitor configuration.
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Color configuration.
. ~/.local/bin/xrdb-export-colors
bspc config active_border_color "$COLOR_0"
bspc config focused_border_color "$COLOR_3"
bspc config normal_border_color "$COLOR_0"
bspc config presel_feedback_color "$COLOR_3"

# bspwm rules.
bspc rule --add Firefox desktop=1
bspc rule --add URxvt:music desktop=0
bspc rule --add URxvt:torrent desktop=8
bspc rule --add Zathura state=tiled
bspc rule --add mpv desktop=9

# Appearance and notifications startup applications.
xsetroot -cursor_name left_ptr
init-daemon compton "compton --config ~/.config/compton/compton.conf" &
init-daemon -r dunst "dunst --config ~/.config/dunst/dunstrc" &
init-daemon notify-battery &
init-daemon robar "robar start" &

# Tray applets.
init-daemon blueman-applet &
init-daemon nm-applet &
init-daemon redshift-gtk &

# Hotkey daemon.
init-daemon sxhkd &

# Urxvtd daemon.
init-daemon urxvtd "urxvtd --quiet --fork --opendisplay"

# Mpd.
init-daemon mpd

# Initialize fonts.
init-fonts

# Initialize displays.
init-displays
bspwm-distribute-desktops
