#!/bin/sh

# Startup applications
## Appearance and notifications
xsetroot -cursor_name left_ptr
init-daemon gsd-xsettings "/usr/lib/gnome-settings-daemon/gsd-xsettings" &
init-daemon compton "compton --config ~/.config/compton/compton.conf" &
init-daemon dunst "dunst --config ~/.config/dunst/dunstrc" &
init-daemon notify-battery &
init-daemon robar "robar start" &

## Tray applets
init-daemon redshift-gtk &
init-daemon blueman-applet &
init-daemon nm-applet &

## Start hotkey daemon
init-daemon sxhkd &

## Initialize displays
init-displays
bspwm-distribute-desktops

## Initialize urxvt daemon
init-daemon urxvtd "urxvtd --quiet --fork --opendisplay"

## Initialize mpd
init-daemon mpd

## Initialize fonts
init-fonts

# Bspwm configuration
bspc config border_width 4
bspc config window_gap 0
bspc config top_padding 21
bspc config bottom_padding 0
bspc config right_padding 0
bspc config left_padding 0

## Monocle configuration
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true

## Pointer configuration
bspc config focus_follows_pointer true
bspc config click_to_focus true

## Monitor configuration
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

## Color configuration
. ~/.local/bin/xrdb-export-colors
bspc config normal_border_color "$COLOR_0"
bspc config active_border_color "$COLOR_0"
bspc config focused_border_color "$COLOR_3"
bspc config presel_feedback_color "$COLOR_3"

## Rules
bspc rule --add Zathura state=tiled
bspc rule --add Firefox desktop=1
bspc rule --add URxvt:music desktop=0
bspc rule --add URxvt:torrent desktop=8
bspc rule --add mpv desktop=9
