#!/usr/bin/env bash

trim() {
  awk '{$1=$1};1'
}

__title() {
  echo "\\033]0;\\u@\\h:\\w\\007"
}

__path_info() {
  echo "\\w"
}

__git_info() {
  # Git not found.
  [ -x "$(which git)" ] || return

  # Force git output in English to make our work easier.
  local git_eng="env LANG=C git"

  # Get current branch name or short SHA1 hash for detached head.
  local branch="$($git_eng symbolic-ref --short HEAD 2>/dev/null || $git_eng describe --tags --always 2>/dev/null)"

  # Git branch not found.
  [ -n "$branch" ] || return

  $git_eng status &>/dev/null || return

  local marks

  local stat="$($git_eng status --porcelain --branch | grep '^##' | grep --only-matching '\[.\+\]$')"
  local all="$($git_eng status --porcelain 2>/dev/null | wc --lines | trim)"
  local unstaged="$($git_eng status --porcelain 2>/dev/null | grep --count "^ \\w" | trim)"
  local uncommited="$($git_eng status --porcelain 2>/dev/null | grep --count "^\\w\\(\\w\\|\\s\\)" | trim)"
  local untracked="$((all - unstaged - uncommited))"
  local ahead="$(echo "$stat" | grep --only-matching 'ahead [[:digit:]]\+' | grep --only-matching '[[:digit:]]\+')"
  local behind="$(echo "$stat" | grep --only-matching 'behind [[:digit:]]\+' | grep --only-matching '[[:digit:]]\+')"

  [ "$untracked" -eq "0" ] || marks+=" $GIT_UNTRACKED_SYMBOL$untracked"
  [ "$unstaged" -eq "0" ] || marks+=" $GIT_UNSTAGED_SYMBOL$unstaged"
  [ "$uncommited" -eq "0" ] || marks+=" $GIT_UNCOMMITED_SYMBOL$uncommited"
  [ -n "$ahead" ] && marks+=" $GIT_NEED_PUSH_SYMBOL$ahead"
  [ -n "$behind" ] && marks+=" $GIT_NEED_PULL_SYMBOL$behind"

  echo "$branch$marks"
}

__venv_info() {
  # venv not found.
  [ -z ${VIRTUAL_ENV+x} ] && return
  version=$(python --version | cut --delimiter=' ' --fields=2-)
  echo "${VIRTUAL_ENV##*/} v$version"
}

__nvm_info() {
  # nvm using system
  version=$(nvm current)
  [ "$version" = "system" ] && return
  echo "nvm $version"
}
