#!/bin/sh

# Easier navigation.
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Interactive and verbose destructive commands
alias rm='rm -iv'
alias mv='mv -iv'
alias cp='cp -iv'

# Safety net
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# Extensions for ls
alias ll='ls -lhF --color=auto'
alias lla='ls -alhF --color=auto'
alias la='ls -aF --color=auto'
alias ls='ls -F --color=auto'

# Colored output
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias diff="diff --color=auto"

# Handy shortcuts
alias h='history'
alias j='jobs -l'
alias mkdir='mkdir -pv'
alias ag='ag --hidden'
alias wget='wget --continue'

# Vim aliases
alias vim='vim --servername VIM'

## Tmux aliases
alias tmux='tmux -f "${XDG_CONFIG_HOME:-$HOME/.config}"/tmux/tmux.conf'

# Add an "alert" alias for long running commands.  Use like so:
# 	sleep 10; alert
alias alert='exit_code=$?; notify-send --urgency=low "$(history | tail --lines=1 | sed --expression '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*ale    rt$//'\'')" "$([ $exit_code = 0 ] && echo Success || echo Error)"'
