#!/bin/sh

CONFIG_DIR=${XDG_CONFIG_HOME:-"$HOME/.config"}/bash

__powerline() {
  ps1() {
    # Check the exit code of the previous command and display different
    # colors in the prompt accordingly.
    if [ $? -eq 0 ]; then
      BG_EXIT="$BG_COLOR_2"
      FG_EXIT="$FG_COLOR_2"
    else
      BG_EXIT="$BG_COLOR_1"
      FG_EXIT="$FG_COLOR_1"
    fi

    PS1="$(__title)"

    git_info="$(__git_info)"

    # Git info
    if [ ! -z "$git_info" ]; then
      PS1="$PS1$BG_COLOR_11$FG_COLOR_15 \\W $RESET$BG_COLOR_4$FG_COLOR_11$RIGHT_ARROW$RESET"
      PS1="$PS1$BG_COLOR_4$FG_COLOR_15 $git_info $RESET$BG_EXIT$FG_COLOR_4$RIGHT_ARROW$RESET"
    else
      PS1="$PS1$BG_COLOR_11$FG_COLOR_15 \\W $RESET$BG_EXIT$FG_COLOR_11$RIGHT_ARROW$RESET"
    fi

    PS1="$PS1$BG_EXIT$FG_COLOR_15 $PS_SYMBOL $RESET$FG_EXIT$RIGHT_ARROW$RESET "
    PS2="$BG_EXIT$FG_COLOR_15 $PS_SYMBOL $RESET$FG_EXIT$RIGHT_ARROW$RESET "
  }
  . "$CONFIG_DIR/bash_symbols"
  . "$CONFIG_DIR/bash_colors"
  . "$CONFIG_DIR/bash_info"
  PROMPT_COMMAND=ps1
}

__powerline
unset __powerline
