#!/bin/sh

__initialize_colors() {
  [ -n "$COLORS_INITIALIZED" ] && return
  readonly COLORS_INITIALIZED=1

  readonly FG_COLOR_0="\\[$(tput setaf 0)\\]"
  readonly FG_COLOR_1="\\[$(tput setaf 1)\\]"
  readonly FG_COLOR_2="\\[$(tput setaf 2)\\]"
  readonly FG_COLOR_3="\\[$(tput setaf 3)\\]"
  readonly FG_COLOR_4="\\[$(tput setaf 4)\\]"
  readonly FG_COLOR_5="\\[$(tput setaf 5)\\]"
  readonly FG_COLOR_6="\\[$(tput setaf 6)\\]"
  readonly FG_COLOR_7="\\[$(tput setaf 7)\\]"
  readonly FG_COLOR_8="\\[$(tput setaf 8)\\]"
  readonly FG_COLOR_9="\\[$(tput setaf 9)\\]"
  readonly FG_COLOR_10="\\[$(tput setaf 10)\\]"
  readonly FG_COLOR_11="\\[$(tput setaf 11)\\]"
  readonly FG_COLOR_12="\\[$(tput setaf 12)\\]"
  readonly FG_COLOR_13="\\[$(tput setaf 13)\\]"
  readonly FG_COLOR_14="\\[$(tput setaf 14)\\]"
  readonly FG_COLOR_15="\\[$(tput setaf 15)\\]"

  readonly BG_COLOR_0="\\[$(tput setab 0)\\]"
  readonly BG_COLOR_1="\\[$(tput setab 1)\\]"
  readonly BG_COLOR_2="\\[$(tput setab 2)\\]"
  readonly BG_COLOR_3="\\[$(tput setab 3)\\]"
  readonly BG_COLOR_4="\\[$(tput setab 4)\\]"
  readonly BG_COLOR_5="\\[$(tput setab 5)\\]"
  readonly BG_COLOR_6="\\[$(tput setab 6)\\]"
  readonly BG_COLOR_7="\\[$(tput setab 7)\\]"
  readonly BG_COLOR_8="\\[$(tput setab 8)\\]"
  readonly BG_COLOR_9="\\[$(tput setab 9)\\]"
  readonly BG_COLOR_10="\\[$(tput setab 10)\\]"
  readonly BG_COLOR_11="\\[$(tput setab 11)\\]"
  readonly BG_COLOR_12="\\[$(tput setab 12)\\]"
  readonly BG_COLOR_13="\\[$(tput setab 13)\\]"
  readonly BG_COLOR_14="\\[$(tput setab 14)\\]"
  readonly BG_COLOR_15="\\[$(tput setab 15)\\]"

  readonly DIM="\\[$(tput dim)\\]"
  readonly REVERSE="\\[$(tput rev)\\]"
  readonly RESET="\\[$(tput sgr0)\\]"
  readonly BOLD="\\[$(tput bold)\\]"

  export FG_COLOR_0
  export FG_COLOR_1
  export FG_COLOR_2
  export FG_COLOR_3
  export FG_COLOR_4
  export FG_COLOR_5
  export FG_COLOR_6
  export FG_COLOR_7
  export FG_COLOR_8
  export FG_COLOR_9
  export FG_COLOR_10
  export FG_COLOR_11
  export FG_COLOR_12
  export FG_COLOR_13
  export FG_COLOR_14
  export FG_COLOR_15

  export BG_COLOR_0
  export BG_COLOR_1
  export BG_COLOR_2
  export BG_COLOR_3
  export BG_COLOR_4
  export BG_COLOR_5
  export BG_COLOR_6
  export BG_COLOR_7
  export BG_COLOR_8
  export BG_COLOR_9
  export BG_COLOR_10
  export BG_COLOR_11
  export BG_COLOR_12
  export BG_COLOR_13
  export BG_COLOR_14
  export BG_COLOR_15

  export DIM
  export REVERSE
  export RESET
  export BOLD
}

__initialize_colors
unset __initialize_colors
