#!/bin/sh

__initialize_formatting() {
  [ -n "$FORMATTING_INITIALIZED" ] && return
  export readonly FORMATTING_INITIALIZED=1

  FG_COLOR_0="\\[$(tput setaf 0)\\]"
  FG_COLOR_1="\\[$(tput setaf 1)\\]"
  FG_COLOR_2="\\[$(tput setaf 2)\\]"
  FG_COLOR_3="\\[$(tput setaf 3)\\]"
  FG_COLOR_4="\\[$(tput setaf 4)\\]"
  FG_COLOR_5="\\[$(tput setaf 5)\\]"
  FG_COLOR_6="\\[$(tput setaf 6)\\]"
  FG_COLOR_7="\\[$(tput setaf 7)\\]"
  FG_COLOR_8="\\[$(tput setaf 8)\\]"
  FG_COLOR_9="\\[$(tput setaf 9)\\]"
  FG_COLOR_10="\\[$(tput setaf 10)\\]"
  FG_COLOR_11="\\[$(tput setaf 11)\\]"
  FG_COLOR_12="\\[$(tput setaf 12)\\]"
  FG_COLOR_13="\\[$(tput setaf 13)\\]"
  FG_COLOR_14="\\[$(tput setaf 14)\\]"
  FG_COLOR_15="\\[$(tput setaf 15)\\]"

  BG_COLOR_0="\\[$(tput setab 0)\\]"
  BG_COLOR_1="\\[$(tput setab 1)\\]"
  BG_COLOR_2="\\[$(tput setab 2)\\]"
  BG_COLOR_3="\\[$(tput setab 3)\\]"
  BG_COLOR_4="\\[$(tput setab 4)\\]"
  BG_COLOR_5="\\[$(tput setab 5)\\]"
  BG_COLOR_6="\\[$(tput setab 6)\\]"
  BG_COLOR_7="\\[$(tput setab 7)\\]"
  BG_COLOR_8="\\[$(tput setab 8)\\]"
  BG_COLOR_9="\\[$(tput setab 9)\\]"
  BG_COLOR_10="\\[$(tput setab 10)\\]"
  BG_COLOR_11="\\[$(tput setab 11)\\]"
  BG_COLOR_12="\\[$(tput setab 12)\\]"
  BG_COLOR_13="\\[$(tput setab 13)\\]"
  BG_COLOR_14="\\[$(tput setab 14)\\]"
  BG_COLOR_15="\\[$(tput setab 15)\\]"

  DIM="\\[$(tput dim)\\]"
  REVERSE="\\[$(tput rev)\\]"
  RESET="\\[$(tput sgr0)\\]"
  BOLD="\\[$(tput bold)\\]"

  export readonly FG_COLOR_0
  export readonly FG_COLOR_1
  export readonly FG_COLOR_2
  export readonly FG_COLOR_3
  export readonly FG_COLOR_4
  export readonly FG_COLOR_5
  export readonly FG_COLOR_6
  export readonly FG_COLOR_7
  export readonly FG_COLOR_8
  export readonly FG_COLOR_9
  export readonly FG_COLOR_10
  export readonly FG_COLOR_11
  export readonly FG_COLOR_12
  export readonly FG_COLOR_13
  export readonly FG_COLOR_14
  export readonly FG_COLOR_15

  export readonly BG_COLOR_0
  export readonly BG_COLOR_1
  export readonly BG_COLOR_2
  export readonly BG_COLOR_3
  export readonly BG_COLOR_4
  export readonly BG_COLOR_5
  export readonly BG_COLOR_6
  export readonly BG_COLOR_7
  export readonly BG_COLOR_8
  export readonly BG_COLOR_9
  export readonly BG_COLOR_10
  export readonly BG_COLOR_11
  export readonly BG_COLOR_12
  export readonly BG_COLOR_13
  export readonly BG_COLOR_14
  export readonly BG_COLOR_15

  export readonly DIM
  export readonly REVERSE
  export readonly RESET
  export readonly BOLD

  export readonly GIT_UNCOMMITED_SYMBOL='+'
  export readonly GIT_UNSTAGED_SYMBOL='*'
  export readonly GIT_UNTRACKED_SYMBOL='?'
  export readonly GIT_NEED_PUSH_SYMBOL='⇡'
  export readonly GIT_NEED_PULL_SYMBOL='⇣'
}

__initialize_formatting
unset __initialize_formatting
