#!/bin/sh

bash_config_dir=${XDG_CONFIG_HOME:-"$HOME/.config"}/bash

__twoline_simple() {
  ps1() {
    # Check the exit code of the previous command and display different
    # colors in the prompt accordingly.
    if [ $? -eq 0 ]; then
      FG_EXIT="$FG_COLOR_2"
    else
      FG_EXIT="$FG_COLOR_1"
    fi

    PS1="$(__title)\\n"

    git_info="$(__git_info)"
    venv_info="$(__venv_info)"
    nvm_info="$(__nvm_info)"

    # Path info
    if [ "$(id -u)" -eq 0 ]; then
      PS1="$PS1$FG_COLOR_4$(__path_info)$RESET"
    else
      PS1="$PS1$FG_COLOR_3$(__path_info)$RESET"
    fi

    # Git info
    [ ! -z "$git_info" ] && PS1="$PS1 on $RESET$FG_COLOR_3$git_info$RESET"

    # Environment info
    existing_info=false
    { [ ! -z "$venv_info" ] || [ ! -z "$nvm_info" ]; } && PS1="$PS1 with"
    for info in "$venv_info" "$nvm_info"; do
      [ -z "$info" ] && continue
      [ "$existing_info" = true ] && PS1="$PS1,"
      PS1="$PS1 $FG_COLOR_3$info$RESET"
      existing_info=true
    done

    PS1="$PS1\\n$FG_EXIT➤ $RESET"
    PS2="$FG_EXIT➤ $RESET"
  }
  . "$bash_config_dir/bash_symbols"
  . "$bash_config_dir/bash_colors"
  . "$bash_config_dir/bash_info"
  PROMPT_COMMAND=ps1
}

__twoline_simple
unset __twoline_simple
