#!/bin/sh

# Easier navigation.
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Interactive and verbose destructive commands.
alias rm='rm -iv'
alias mv='mv -iv'
alias cp='cp -iv'

# Safety net.
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# Extensions for ls.
alias ll='ls -lhF --color=auto'
alias lla='ls -alhF --color=auto'
alias la='ls -aF --color=auto'
alias ls='ls -F --color=auto'

# Colored output.
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias diff='diff --color=auto'

# Handy shortcuts.
alias tmux-update-env='eval $(tmux show-environment -s)'
alias vi='nvim'
alias vim='nvim'
alias wget='wget --continue'
