#!/bin/sh

# Create directory and cd into.
mcd() {
  mkdir -p "$1" && cd "$1"
}

# Print pid, cpu usage percentage, and process name of the processes consuming
# the most cpu.
process_cpu() {
  count=${1:-10}
  ps aux --sort '%cpu' | awk '{print $2, $3, $11}' | tail -n "$count" | tac
}

# Print pid, memory usage percentage, and process name of the processes consuming
# the most memory.
process_mem() {
  count=${1:-10}
  ps aux --sort '%mem' | awk '{print $2, $4, $11}' | tail -n "$count" | tac
}
