#!/bin/sh

__initialize_symbols() {
  [ -n "$SYMBOLS_INITIALIZED" ] && return
  readonly SYMBOLS_INITIALIZED=1

  # Git symbols.
  readonly GIT_UNCOMMITED_SYMBOL='+'
  export GIT_UNCOMMITED_SYMBOL
  readonly GIT_UNSTAGED_SYMBOL='*'
  export GIT_UNSTAGED_SYMBOL
  readonly GIT_UNTRACKED_SYMBOL='?'
  export GIT_UNTRACKED_SYMBOL
  readonly GIT_NEED_PUSH_SYMBOL='⇡'
  export GIT_NEED_PUSH_SYMBOL
  readonly GIT_NEED_PULL_SYMBOL='⇣'
  export GIT_NEED_PULL_SYMBOL
}

__initialize_symbols
unset __initialize_symbols
