#!/bin/sh

: <<'solarized color scheme'
if [ "$(tput colors)" -ge 256 ] 2>/dev/null; then
  readonly FG_COLOR_0="\\[$(tput setaf 235)\\]"
  readonly FG_COLOR_1="\\[$(tput setaf 160)\\]"
  readonly FG_COLOR_2="\\[$(tput setaf 64)\\]"
  readonly FG_COLOR_3="\\[$(tput setaf 136)\\]"
  readonly FG_COLOR_4="\\[$(tput setaf 33)\\]"
  readonly FG_COLOR_5="\\[$(tput setaf 125)\\]"
  readonly FG_COLOR_6="\\[$(tput setaf 37)\\]"
  readonly FG_COLOR_7="\\[$(tput setaf 254)\\]"
  readonly FG_COLOR_8="\\[$(tput setaf 234)\\]"
  readonly FG_COLOR_9="\\[$(tput setaf 166)\\]"
  readonly FG_COLOR_10="\\[$(tput setaf 240)\\]"
  readonly FG_COLOR_11="\\[$(tput setaf 241)\\]"
  readonly FG_COLOR_12="\\[$(tput setaf 244)\\]"
  readonly FG_COLOR_13="\\[$(tput setaf 61)\\]"
  readonly FG_COLOR_14="\\[$(tput setaf 245)\\]"
  readonly FG_COLOR_15="\\[$(tput setaf 230)\\]"

  readonly BG_COLOR_0="\\[$(tput setab 235)\\]"
  readonly BG_COLOR_1="\\[$(tput setab 160)\\]"
  readonly BG_COLOR_2="\\[$(tput setab 64)\\]"
  readonly BG_COLOR_3="\\[$(tput setab 136)\\]"
  readonly BG_COLOR_4="\\[$(tput setab 33)\\]"
  readonly BG_COLOR_5="\\[$(tput setab 125)\\]"
  readonly BG_COLOR_6="\\[$(tput setab 37)\\]"
  readonly BG_COLOR_7="\\[$(tput setab 254)\\]"
  readonly BG_COLOR_8="\\[$(tput setab 234)\\]"
  readonly BG_COLOR_9="\\[$(tput setab 166)\\]"
  readonly BG_COLOR_10="\\[$(tput setab 240)\\]"
  readonly BG_COLOR_11="\\[$(tput setab 241)\\]"
  readonly BG_COLOR_12="\\[$(tput setab 244)\\]"
  readonly BG_COLOR_13="\\[$(tput setab 61)\\]"
  readonly BG_COLOR_14="\\[$(tput setab 245)\\]"
  readonly BG_COLOR_15="\\[$(tput setab 230)\\]"
fi
solarized color scheme

__initialize_colors() {
  [ -n "$COLORS_INITIALIZED" ] && return
  readonly COLORS_INITIALIZED=1

  readonly FG_COLOR_0="\\[$(tput setaf 0)\\]"
  readonly FG_COLOR_1="\\[$(tput setaf 1)\\]"
  readonly FG_COLOR_2="\\[$(tput setaf 2)\\]"
  readonly FG_COLOR_3="\\[$(tput setaf 3)\\]"
  readonly FG_COLOR_4="\\[$(tput setaf 4)\\]"
  readonly FG_COLOR_5="\\[$(tput setaf 5)\\]"
  readonly FG_COLOR_6="\\[$(tput setaf 6)\\]"
  readonly FG_COLOR_7="\\[$(tput setaf 7)\\]"
  readonly FG_COLOR_8="\\[$(tput setaf 8)\\]"
  readonly FG_COLOR_9="\\[$(tput setaf 9)\\]"
  readonly FG_COLOR_10="\\[$(tput setaf 10)\\]"
  readonly FG_COLOR_11="\\[$(tput setaf 11)\\]"
  readonly FG_COLOR_12="\\[$(tput setaf 12)\\]"
  readonly FG_COLOR_13="\\[$(tput setaf 13)\\]"
  readonly FG_COLOR_14="\\[$(tput setaf 14)\\]"
  readonly FG_COLOR_15="\\[$(tput setaf 15)\\]"

  readonly BG_COLOR_0="\\[$(tput setab 0)\\]"
  readonly BG_COLOR_1="\\[$(tput setab 1)\\]"
  readonly BG_COLOR_2="\\[$(tput setab 2)\\]"
  readonly BG_COLOR_3="\\[$(tput setab 3)\\]"
  readonly BG_COLOR_4="\\[$(tput setab 4)\\]"
  readonly BG_COLOR_5="\\[$(tput setab 5)\\]"
  readonly BG_COLOR_6="\\[$(tput setab 6)\\]"
  readonly BG_COLOR_7="\\[$(tput setab 7)\\]"
  readonly BG_COLOR_8="\\[$(tput setab 8)\\]"
  readonly BG_COLOR_9="\\[$(tput setab 9)\\]"
  readonly BG_COLOR_10="\\[$(tput setab 10)\\]"
  readonly BG_COLOR_11="\\[$(tput setab 11)\\]"
  readonly BG_COLOR_12="\\[$(tput setab 12)\\]"
  readonly BG_COLOR_13="\\[$(tput setab 13)\\]"
  readonly BG_COLOR_14="\\[$(tput setab 14)\\]"
  readonly BG_COLOR_15="\\[$(tput setab 15)\\]"

  readonly DIM="\\[$(tput dim)\\]"
  readonly REVERSE="\\[$(tput rev)\\]"
  readonly RESET="\\[$(tput sgr0)\\]"
  readonly BOLD="\\[$(tput bold)\\]"
}

__initialize_colors
unset __initialize_colors
